### PR TITLE
add `ffi` cheatcode

### PR DESCRIPTION
**Pull request by luksgrin**
This PR contains the implementation of Foundry's `function ffi(string[] calldata) external returns (bytes memory);` cheatcode with some helper functions and some code refactoring. [See `ffi`'s documentation here](https://book.getfoundry.sh/cheatcodes/ffi).

**Dependencies added**
- Python's native `subprocess` module

### CODE REVIEW

**Comment by luksgrin** [comment]
I am aware that both [`extract_string_argument`](https://github.com/a16z/halmos/blob/29f90f0a206c7f5c63a7966101c816b4eb97e3d2/src/halmos/sevm.py#L395) and [`extract_string_array_argument`](https://github.com/a16z/halmos/blob/29f90f0a206c7f5c63a7966101c816b4eb97e3d2/src/halmos/sevm.py#L414) share a lot of logic. But I did not want to risk breaking [`extract_string_argument`](https://github.com/a16z/halmos/blob/29f90f0a206c7f5c63a7966101c816b4eb97e3d2/src/halmos/sevm.py#L395) for a silly refactoring...

**Comment by luksgrin** [comment]
@daejunpark Please let me know if the tests I added are enough. I wanted to add one to test execution failure, but there is no `expectRevert` cheatcode... Possibly a `# TODO`?

**Comment by luksgrin** [comment]
> looks good, thanks @luksgrin! I'll make a couple small changes to have CI pass directly to the branch if you don't mind

No problem! Thanks😄

**Review by karmacoma-eth — APPROVED** [review]

**Comment by daejunpark** [comment]
> @daejunpark Please let me know if the tests I added are enough. I wanted to add one to test execution failure, but there is no `expectRevert` cheatcode... Possibly a `# TODO`?

Awesome! Currently, you can use the expected json exitcode to test the failure cases. Please feel free to add negative tests if you already have something in mind.

**Comment by luksgrin** [comment]
> > @daejunpark Please let me know if the tests I added are enough. I wanted to add one to test execution failure, but there is no `expectRevert` cheatcode... Possibly a `# TODO`?
> 
> Awesome! Currently, you can use the expected json exitcode to test the failure cases. Please feel free to add negative tests if you already have something in mind.

I had one but I removed it! I will write it again so that we can add it 😃

**Comment by luksgrin** [comment]
> > > @daejunpark Please let me know if the tests I added are enough. I wanted to add one to test execution failure, but there is no `expectRevert` cheatcode... Possibly a `# TODO`?
> > 
> > 
> > Awesome! Currently, you can use the expected json exitcode to test the failure cases. Please feel free to add negative tests if you already have something in mind.
> 
> I had one but I removed it! I will write it again so that we can add it 😃

Done!

**Comment by daejunpark** [comment]
Thank you!  Let me reorg the pytest tests to exclude the ffi tests on windows.

**Comment by daejunpark** [comment]
@luksgrin I've modified the semantics of `ffi` so that it does _not_ fail (but generates an warning) when stderr is present, in order to align with Foundry's behavior:
https://github.com/a16z/halmos/pull/185/commits/57241d869ae8b8603130a3ef9d00a3fb5bf42042

**Comment by daejunpark** [comment]
@luksgrin let me go ahead and merge this for now, as it's been open for quite some time. we can create a separate pr if the semantics of ffi needs to be improved. thanks for your contribution!

**Comment by luksgrin** [comment]
Tysm for merging! I believe it is a perfect choice to imitate foundry's default behavior :)

**Pull request merged**
