### PR TITLE
perf: use to_smt2() instead of sexpr() for assertion solving

### PR DESCRIPTION
**Pull request by daejunpark**
not entirely sure about this, but may be worth considering.

in certain cases, sexpr() is significantly slower than to_smt2(), but haven't seen the opposite yet.

### CODE REVIEW

**Review by karmacoma-eth — APPROVED** [review]
if it works let's go for it 👍

speaking of which, looks like CI is not running for this PR? 🤨

**Comment by daejunpark** [comment]
> speaking of which, looks like CI is not running for this PR? 🤨

that's because it's not based on main.

**Comment by karmacoma-eth** [comment]
> that's because it's not based on main.

ah makes sense, do we want to keep it this way though?

**Comment by daejunpark** [comment]
> > that's because it's not based on main.
> 
> ah makes sense, do we want to keep it this way though?

yeah let's enable tests for this as well.  perhaps, it's good time to review the overall settings and update things that can be improved?  would you be able to take a look with fresh mind?

**Pull request merged**
